### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Pointemorte** [Zafireria/Medieval-Overhaul-Lite#1]
Make the "Steel Grill" use the VE's "Grill" bills 
Add the "Steel Grill" to the "Grilling" research
Allow timbers, cupboards, sacks, meat/hay racks, carts, bookshelves, barrels, and crates to store items (deep storage integration)
Allow the "water filled barrel" to store water (dubs bad hygiene integration)
Make the "Smoker" use the VE's "meat smoker" bills
Give the "Oven" and the "Large oven" bakery-related bills from the Vanilla Cooking Expanded
Allow the "Spinning wheel" to process the "Raw cotton" (seeds please: lite integration)
Remove bills from the "Hearth"
Consider turning the "Bird post" into a prop
Give the "Stew pot" stew-related bills from Vanilla Cooking Expanded
Limit food bills related to the "Millstone" to simple vegetarian ones
Add a "cleanliness" bonus to the "Cleaning bench"
Add the "Apiary" to the "Bee keeping" research
Make the Apiary" use the VFE Viking's "Apiary" bills 
Consider merging non-useful items with the VE's Props tab and research
Allow the "Jewelry table" to create jewelry from this mod https://steamcommunity.com/sharedfiles/filedetails/?id=2020964421&searchtext=jewelry
Lock all of the furniture behind some kind of research

**Comment by Zafireria** [comment]
Most of those requires to be patched with other mods which is not something I want to fiddle with right now. But I can take a look at the rest. 

Also furniture are behind research, you need to have "Complex Furniture" unlocked. Most starting scenarios starts with that already unlocked except for tribes. The rest is also behind research, custom one.  

With "Bee Research" I assume you mean Alpha Bees?

**Comment by Pointemorte** [comment]
`With "Bee Research" I assume you mean Alpha Bees?`
That thing is added by VFE Vikings

**Comment by Pointemorte** [comment]
Some of the buildings, such as the "Cheese shelf", need to have their real size reduced. Despite having small textures, they take up a lot of space

**Comment by Pointemorte** [comment]
Rotation settings for carts allow the player to place them upside down

**Comment by Zafireria** [comment]
> `With "Bee Research" I assume you mean Alpha Bees?` That thing is added by VFE Vikings

There is mod called "Alpha Bees" that also adds bees. 



> Some of the buildings, such as the "Cheese shelf", need to have their real size reduced. Despite having small textures, they take up a lot of space

I believe they are the original sizes, I did have to resize the small shelf tho, as they were way to big. If I am thinking of the correct shelf you are on about, I think they are suppose to be that big, they are not shelf in that sense they are more like pallets with walls, if that makes sense, lol. 


> Rotation settings for carts allow the player to place them upside down

Not sure I understand? Why would you want to turn them upside down?

**Comment by Pointemorte** [comment]
Vanilla game doesn't allow players to place textures upside down. This is a visual bug.
Physical size of objects such as the "Cheese shelf" is bigger than the visual one. For ex. a 4x4 texture occupies 6x6 space (clicking on it reveals its full size)

**Comment by Zafireria** [comment]
Right so I have had a look at the issues both in files and in game.

- The cleaning bench is already adding cleanness to a room, it's at 5.0.
- I see what you mean with the draw problem on the cheese shelf and others, but not sure how to fix that, both <size> and <drawSize> are the same number, so it should match. I did resize it tho, so the "border" is probably the original size of the item. I'll try and figured out how to fix it.
- Is there a reason why you want the Hearth to have no bills? It's only able to make simple things like simple meal, pemmican and baby food, as well as burn stuff. 
- The other stuff you have managed sounds great to add, but they require patches, which I might add eventually but not a top prio, I am open for to other people making patches to this etc. 
- Rotation on the carts are fixed in the update.

**Comment by Zafireria** [comment]
Right so I have had a look at the issues both in files and in game.

The cleaning bench is already adding cleanness to a room, it's at 5.0.
I see what you mean with the draw problem on the cheese shelf and others, but not sure how to fix that, both and are the same number, so it should match. I did resize it tho, so the "border" is probably the original size of the item. I'll try and figured out how to fix it.
Is there a reason why you want the Hearth to have no bills? It's only able to make simple things like simple meal, pemmican and baby food, as well as burn stuff.
The other stuff you have managed sounds great to add, but they require patches, which I might add eventually but not a top prio, I am open for to other people making patches to this etc.
Rotation on the carts are fixed in the update.


I am not sure why the topic is suddenly marked "Closed" when it's not, GitHub is complicated lol.

**Comment by Pointemorte** [comment]
> Right so I have had a look at the issues both in files and in game.
> 
> The cleaning bench is already adding cleanness to a room, it's at 5.0. I see what you mean with the draw problem on the cheese shelf and others, but not sure how to fix that, both and are the same number, so it should match. I did resize it tho, so the "border" is probably the original size of the item. I'll try and figured out how to fix it. Is there a reason why you want the Hearth to have no bills? It's only able to make simple things like simple meal, pemmican and baby food, as well as burn stuff. The other stuff you have managed sounds great to add, but they require patches, which I might add eventually but not a top prio, I am open for to other people making patches to this etc. Rotation on the carts are fixed in the update.
> 
> I am not sure why the topic is suddenly marked "Closed" when it's not, GitHub is complicated lol.

Allowing the "Hearth" to cook makes all of the other mods adding furniture inconsistent since they make such things serve the sole purpose of being a decoration. In my game, I limited its use to burning stuff.
